// Generated by scripts/build/design_tokens.py from assets/theme/design_tokens.json and
// assets/theme/icon_mapping.json, the one source both clients share (R19). Do not edit this
// file: change the source and run the script again.

/**
 * The Nexees design tokens: colours as #rrggbb, shares of a whole in percent in the groups
 * whose names end in `_percent`, and every other value in CSS pixels.
 */
export const TOKENS = {
    color: {
        surface: {
            window: '#0b1017',
            editor: '#0e131b',
            raised: '#161d29',
            hover: '#121923',
            selected: '#182030',
        },
        border: {
            subtle: '#232c3b',
        },
        text: {
            primary: '#e2e8f0',
            secondary: '#a9b6cb',
            muted: '#7c8aa0',
            on_accent: '#ffffff',
        },
        accent: {
            primary: '#3d9df7',
            secondary: '#c26bf2',
            fill: '#2468d8',
            fill_hover: '#2a72e0',
        },
        status: {
            success: '#2ecc5f',
            warning: '#e5b93c',
            error: '#f2555a',
        },
        syntax: {
            keyword: '#c97fd6',
            string: '#e58a5c',
            number: '#e3b566',
            function: '#3cb4ee',
            type: '#56c8d8',
            variable: '#7fb0f8',
        },
    },
    font: {
        base: 13,
        small: 12,
    },
    space: {
        unit: 6,
    },
    radius: {
        control: 4,
    },
    desktop: {
        row_height: 22,
        tab_height: 35,
        status_bar_height: 22,
        activity_bar_width: 48,
        title_bar_height: 25,
        title_logo_size: 16,
        sidebar_toggle_width: 24,
        window_control_width: 30,
    },
    desktop_percent: {
        left_sidebar_width: 19,
        right_sidebar_width: 41,
        bottom_panel_height: 27,
    },
} as const;

/** The Nexees icon language: the name of the Codicon that stands for each concept. */
export const ICONS = {
    host_attached: 'plug',
    host_attaching: 'sync',
    host_unavailable: 'warning',
    sidebar_left_shown: 'layout-sidebar-left',
    sidebar_left_hidden: 'layout-sidebar-left-off',
    sidebar_right_shown: 'layout-sidebar-right',
    sidebar_right_hidden: 'layout-sidebar-right-off',
    area_agent: 'hubot',
    area_lcl: 'law',
    area_tasks: 'checklist',
    area_chat: 'comment-discussion',
    area_logs: 'output',
} as const;
